name: Lint Markdown

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Lint Markdown
        uses: ./
        with:
          files: './README.md'
